version: '3'
services:

  rstudio:
    environment:
      - PASSWORD=minidream
      - ROOT=TRUE
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home:/home
    ports:
      - "8787:8787"

